### ISSUE TITLE
Try to change from Board& to char&

### ISSUE THREAD

**Issue by Mark5589** [BarZamsky/Ex6-Board#1]
https://github.com/BarZamsky/Ex6-Board/blob/250205623a5173a530131843230b56972e778fd5/Board.cpp#L46

**Comment by Mark5589** [comment]
Hey there!
just checked your profile because i was stuck with the understanding of the meaning Board[{int,int}] , now i see that was just regular array... doh
so ... if you want the access to some specific place "matrix[1,1]" for example , try to return char& s.t it will return the reference place of the matrix char board... (worked for me)

**Comment by BarZamsky** [comment]
hey!! thank  you dear mark
